// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolWebAdmin.Models;

#nullable disable

namespace SchoolWebAdmin.Migrations
{
    [DbContext(typeof(SchoolDatabaseContext))]
    [Migration("20231017025607_initial-create")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolWebAdmin.Models.DepartmentTable", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCDB6C17AAF");

                    b.ToTable("DepartmentTable", (string)null);
                });

            modelBuilder.Entity("SchoolWebAdmin.Models.StudentTable", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Semester")
                        .HasColumnType("int");

                    b.HasKey("StudentId")
                        .HasName("PK__StudentT__32C52A79F343DF2C");

                    b.HasIndex("DepartmentId");

                    b.ToTable("StudentTable", (string)null);
                });

            modelBuilder.Entity("SchoolWebAdmin.Models.StudentTable", b =>
                {
                    b.HasOne("SchoolWebAdmin.Models.DepartmentTable", "Department")
                        .WithMany("StudentTables")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__StudentTa__Depar__35BCFE0A");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolWebAdmin.Models.DepartmentTable", b =>
                {
                    b.Navigation("StudentTables");
                });
#pragma warning restore 612, 618
        }
    }
}
